'use strict';

/**
 * browser — 浏览器自动化扩展（builtin 轻壳，doc-extract 同款模式）。
 *
 * 引擎本体在内核（src/kernel/browser/**，Playwright 跑在内核主线程）：扩展运行于
 * worker_threads + vm.Context 沙箱，受限 require 只放行扩展目录内相对 .js，Playwright
 * （npm 包 + child_process + node:fs）在沙箱内不可加载——探针证据见本目录 README.md。
 *
 * 本扩展只做三件事（auth:'user' 扩展路由）：
 * - GET  /api/status            → 引擎运行态 { installed, running, installing, lastError }
 * - POST /install               → 幂等触发后台安装 chromium（立即返回，不等完成）
 * - GET  /screenshots/:file     → 截图 PNG（:file 必须是 browser_screenshot 产出的
 *                                 <uuid>.png；uuid 形状校验防路径穿越）
 *
 * LLM 工具面（browser_navigate / browser_snapshot / browser_click / browser_type /
 * browser_press_key / browser_screenshot / browser_close / browser_status）由内核直接
 * 提供（/mcp 系统工具），不经本扩展转发——与 doc-extract（files_extract）同模式。
 * 沙箱内禁 console 系列；错误统一收敛为结构化响应体，不向内核路由层抛裸异常。
 */

defineExtension(async (h) => {
  /**
   * HarnessApi 子集（本扩展实际使用面；完整契约见仓库 types/harness.d.ts）。
   * @property {{ status(): Promise<{installed: boolean, running: boolean, installing: boolean, lastError: string | null}>, install(): Promise<{started: boolean, installed?: boolean, installing?: boolean}>, readScreenshot(file: string): Promise<{file: string, mime: string, base64: string}> }} browser 浏览器内核引擎门面（manifest 'browser' 权限）
   * @property {{ error(msg: unknown, obj?: unknown): void, info(msg: unknown, obj?: unknown): void }} log
   */

  /** 截图文件名形状：<uuid>.png（防穿越第一道闸；引擎侧同规则复核） */
  var SCREENSHOT_FILE_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.png$/i;

  /** HarnessError code → HTTP 状态（桥错误经 RPC 信封保留 HARNESS-* 全码） */
  function statusOf(code) {
    if (code === 'HARNESS-3004' || code === 'HARNESS-2002') return 404; // EXT_NOT_FOUND / RPC_TARGET_NOT_FOUND
    if (code === 'HARNESS-1007' || code === 'HARNESS-2003') return 403; // FORBIDDEN / RPC_PERMISSION_DENIED
    if (code === 'HARNESS-1008') return 400; // BAD_REQUEST
    return 500;
  }

  /** 统一错误响应：结构化 { error, message }，不泄露内核堆栈 */
  function errorResponse(e) {
    var code = e && typeof e.code === 'string' ? e.code : 'INTERNAL';
    return {
      status: statusOf(code),
      body: {
        error: code,
        message: e && typeof e.message === 'string' ? e.message : String(e),
      },
    };
  }

  // ---------------------------------------------------------------- 状态路由

  h.route('GET', '/api/status', async function () {
    try {
      var st = await h.browser.status();
      return {
        status: 200,
        body: {
          extension: 'browser',
          installed: st.installed === true,
          running: st.running === true,
          installing: st.installing === true,
          lastError: st.lastError === undefined ? null : st.lastError,
        },
      };
    } catch (e) {
      return errorResponse(e);
    }
  }, { auth: 'user' });

  // ---------------------------------------------------------------- 安装路由

  h.route('POST', '/install', async function () {
    try {
      var result = await h.browser.install();
      return { status: 200, body: result };
    } catch (e) {
      return errorResponse(e);
    }
  }, { auth: 'user' });

  // ---------------------------------------------------------------- 截图路由

  h.route('GET', '/screenshots/:file', async function (request) {
    var file = request && request.params ? String(request.params.file || '') : '';
    if (!SCREENSHOT_FILE_RE.test(file)) {
      return {
        status: 400,
        body: {
          error: 'browser_screenshot_name_invalid',
          message: 'screenshot file must be a "<uuid>.png" generated by browser_screenshot',
        },
      };
    }
    try {
      var shot = await h.browser.readScreenshot(file);
      return {
        status: 200,
        headers: { 'content-type': shot.mime || 'image/png', 'cache-control': 'no-store' },
        body: base64ToBinaryString(shot.base64),
      };
    } catch (e) {
      return errorResponse(e);
    }
  }, { auth: 'user' });

  /**
   * 纯 JS base64 → 二进制字符串（沙箱无 Buffer/atob；latin1 字符串跨线程结构化克隆
   * 安全，内核侧以 image/png 原样回写）。实现：6bit 累积器按 8bit 切分。
   */
  function base64ToBinaryString(input) {
    var CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
    var out = '';
    var buffer = 0;
    var bits = 0;
    for (var i = 0; i < input.length; i += 1) {
      var ch = input.charAt(i);
      if (ch === '=' || ch === '\n' || ch === '\r') continue;
      var v = CHARS.indexOf(ch);
      if (v < 0) throw new Error('invalid base64 payload in screenshot data');
      buffer = ((buffer & 0x3f) << 6) | v;
      bits += 6;
      if (bits >= 8) {
        bits -= 8;
        out += String.fromCharCode((buffer >> bits) & 0xff);
      }
    }
    return out;
  }
});
