/**
 * browser/types — 浏览器自动化内核引擎的共享契约。
 *
 * 引擎本体（engine.ts）跑在内核主线程（方案 B：doc-extract 模式——扩展只是
 * manifest+路由壳，Playwright 无法在扩展沙箱内加载，探针证据见扩展 README）：
 * - 单例浏览器上下文（同一时间至多一个 Browser + 一个 Page，mutex 串行化）；
 * - 10 分钟空闲自动关浏览器（下轮工具调用再冷启动）；
 * - 工具调用时浏览器已死则自动重启一次（崩溃恢复）；
 * - 页面导航超时 30s；URL 仅允许 http/https（禁 file:// 与其余协议）；
 * - 浏览器二进制默认不下载：未安装时统一收敛为 BrowserNotInstalledError，
 *   由工具层映射为 `{ error: 'browser_not_installed', hint }` 结构化错误。
 */

/** 浏览器未安装（chromium 可执行文件缺失）的结构化错误标记类 */
export class BrowserNotInstalledError extends Error {
  readonly code = 'browser_not_installed' as const;
  readonly hint: string;
  constructor(hint = 'run POST /ext/browser/install (auth:user) to install chromium in the background, or `node node_modules/playwright-core/cli.js install chromium` on the host') {
    super('chromium is not installed for playwright-core (browser binaries are not downloaded by default)');
    this.name = 'BrowserNotInstalledError';
    this.hint = hint;
  }
}

/** URL 校验失败（非 http/https 协议、file://、语法非法） */
export class BrowserUrlRejectedError extends Error {
  readonly code = 'browser_url_rejected' as const;
  readonly url: string;
  constructor(url: string, reason: string) {
    super(`url rejected: ${reason} (only http/https is allowed; file:// and other schemes are blocked)`);
    this.name = 'BrowserUrlRejectedError';
    this.url = url;
  }
}

/** 引擎忙：mutex 等待队列已满（同一时间仅一个浏览器实例 + 有限排队） */
export class BrowserBusyError extends Error {
  readonly code = 'browser_busy' as const;
  constructor(queueLimit: number) {
    super(`browser engine is busy: ${queueLimit} operations already queued (single browser instance)`);
    this.name = 'BrowserBusyError';
  }
}

/** 安装器不可用（playwright-core CLI 缺失等）：install 路由的结构化失败 */
export class BrowserInstallUnavailableError extends Error {
  readonly code = 'browser_install_unavailable' as const;
  constructor(detail: string) {
    super(`browser installer is unavailable: ${detail}`);
    this.name = 'BrowserInstallUnavailableError';
  }
}

/** 截图文件名非法（非 uuid 形状，防路径穿越） */
export class BrowserScreenshotNameError extends Error {
  readonly code = 'browser_screenshot_name_invalid' as const;
  constructor(file: string) {
    super(`screenshot file must be a "<uuid>.png" generated by browser_screenshot (got "${file.slice(0, 80)}")`);
    this.name = 'BrowserScreenshotNameError';
  }
}

/** 浏览器运行态快照（GET /ext/browser/api/status 与工具诊断共用形状） */
export interface BrowserStatus {
  /** chromium 可执行文件是否已安装 */
  installed: boolean;
  /** 当前是否有存活的浏览器实例 */
  running: boolean;
  /** 后台安装是否进行中 */
  installing: boolean;
  /** 最近一次错误（null = 无） */
  lastError: string | null;
}

/** browser_navigate 结果 */
export interface BrowserNavigateResult {
  title: string;
  url: string;
  status: number;
}

/** browser_snapshot 结果 */
export interface BrowserSnapshotResult {
  snapshot: string;
  truncated: boolean;
}

/** browser_click 入参 */
export interface BrowserClickInput {
  selector: string;
}

/** browser_type 入参 */
export interface BrowserTypeInput {
  selector: string;
  text: string;
}

/** browser_press_key 入参 */
export interface BrowserPressKeyInput {
  key: string;
}

/** browser_screenshot 入参（targetDir 为工作区落盘覆写，见 BrowserScreenshotResult） */
export interface BrowserScreenshotInput {
  fullPage?: boolean;
  /** 截图落盘目录覆写（绝对路径，通常是 <对话工作区>/screenshots；目录不存在即建） */
  targetDir?: string;
}

/**
 * browser_screenshot 结果。两种模式：
 * - 缺省（数据目录）：path 为绝对路径，url 为扩展路由 /ext/browser/screenshots/:file；
 * - targetDir 覆写（对话工作区）：path 为工作区相对路径 `screenshots/<file>`，
 *   url 为空串（由工具层按 REST 预览端点拼装，引擎不做 URL 策略）。
 */
export interface BrowserScreenshotResult {
  path: string;
  file: string;
  url: string;
}

/** browser_install 结果（幂等语义） */
export interface BrowserInstallResult {
  /** 本次调用是否真正触发了后台安装 */
  started: boolean;
  /** 已安装（无需再装） */
  installed?: boolean;
  /** 已有安装任务进行中（本次未重复触发） */
  installing?: boolean;
}

/** 截图读取结果（扩展壳转 PNG 响应用） */
export interface BrowserScreenshotFile {
  file: string;
  mime: 'image/png';
  base64: string;
}

// ---------------------------------------------------------------------------
// 常量（引擎与工具层共用，勿散落魔法数）
// ---------------------------------------------------------------------------

/** 页面导航/操作超时（毫秒） */
export const BROWSER_NAV_TIMEOUT_MS = 30_000;

/** 快照文本截断上限（50KB，UTF-8 字节口径） */
export const BROWSER_SNAPSHOT_MAX_BYTES = 50 * 1024;

/** 空闲自动关浏览器阈值（毫秒）：10 分钟无调用即关（下轮调用再冷启动） */
export const BROWSER_IDLE_CLOSE_MS = 10 * 60_000;

/** mutex 等待队列深度上限：超出直接 BUSY（防无界排队拖垮内核主线程） */
export const BROWSER_QUEUE_LIMIT = 16;

/** 截图文件名形状：<uuid>.png（防穿越的唯一合法形状） */
export const SCREENSHOT_FILE_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.png$/i;
